<<<<<<< HEAD
# Write a program input eight number is from the user and display all the unique number is (once)

s = set()
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))

print(s)
=======
# Write a program input eight number is from the user and display all the unique number is (once)

s = set()
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))
a = input("Enter the number :")
s.add(int(a))

print(s)
>>>>>>> 99a1cafa93f0df4171e270c79c0de78744a77b8e
# print(len(s))